# 站点信息
site_name: Forensics-Wiki
site_url: https://www.forensics-wiki.com
site_author: Forensics-Wiki
site_description: 电子数据取证Wiki

# 仓库信息
repo_name: Forensics-Wiki
repo_url: https://github.com/Forensics-wiki/Forensics-Wiki
edit_uri: https://github.com/Forensics-wiki/Forensics-Wiki/tree/main/docs/

# 版权
copyright: CC BY-NC-SA 4.0 协议

# 自定义统计
extra_javascript:
  - js/clarity.js

extra:
  generator: false
  # 页脚社交媒体
  social:
    - icon: fontawesome/brands/qq 
      link: https://jq.qq.com/?_wv=1027&k=2myrMcmN
    - icon: fontawesome/brands/github
      link: https://github.com/Forensics-wiki/Forensics-Wiki

# 扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 主题设置
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  custom_dir: overrides
  language: zh
  features:
    # - announce.dismiss        # 通知关闭
    - content.action.edit       # 编辑操作
    - content.action.view       # 查看操作
    - content.code.annotate     # 代码注释
    - content.code.copy         # 复制代码
    - content.tabs.link         # 标签链接
    - content.tooltips          # 工具提示
    # - header.autohide         # 自动隐藏头部
    # - navigation.expand       # 展开导航
    - navigation.indexes        # 导航索引
    - navigation.instant      # 即时导航
    # - navigation.prune        # 导航修剪
    # - navigation.sections     # 导航节
    - navigation.tabs         # 导航标签
    # - navigation.tabs.sticky  # 固定导航标签
    - navigation.top            # 导航顶部
    - navigation.footer         # 导航底部
    - navigation.tracking       # 导航跟踪
    - search.highlight          # 搜索高亮
    - search.share              # 搜索分享
    - search.suggest            # 搜索建议
    - toc.follow                # 目录跟随
    # - toc.integrate           # 目录整合

  # 调色板配置  
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # 字体配置        
  font:
    text: Noto Sans SC
    code: Fira Code

nav:
  - 首页:
      - 电子数据取证Wiki: index.md
      - 目录结构🏠: table.md
      - 加入我们👥: join.md
  - 引言:
      - 电子数据取证引入: index/yr.md
      - 商业软件授权问题: index/sq.md
  - 取证基础:
      - 哈希值: base/hash.md
      - VeraCrypt使用方法: base/veracrypt.md
      - 证据文件格式: base/gs.md
      - 镜像制作: base/zz.md
      - 镜像仿真-DD、E01: base/dd.md
      - 镜像仿真-Windows Server: base/win.md
      - 常见的时间戳转换: base/time.md
      - 各类文件打开方式: base/openfiles.md
  - Windows取证:
      - Bitlocker加密与解密: windows/bitlocker.md
      - EFS加密与解密: windows/efs.md
      - 注册表取证: windows/zc.md
  - Linux&服务器取证:
      - 介绍: linux/intr.md
      - 基础命令: linux/basecommand.md
      - CDN基础: linux/cdn.md
      - 宝塔面板取证: linux/bt.md
      - 常见webshell工具流量特征: linux/webshell.md
      - 通过.frm和.idb文件恢复mysql数据库: linux/sql.md
      - 新版宝塔加密数据解密: linux/newbt.md
      - PVE 7.2 iso 镜像重置 pve root密码: linux/pvere.md
      - java网站重建绕密常用技巧: linux/javapass.md
  - 内存取证:
      - 介绍: volatility/js.md
      - 安装: volatility/install.md
      - Windows基本用法: volatility/Windowsbase.md
      - Windows命令参考: volatility/Windowscmd.md
      - Win-Profiles : volatility/profile.md
      - MemProcFS: volatility/MemProcFS.md
  - 安卓取证:
      - 彩信/短信取证: android/sms.md
      - Android数据存储技术: android/data.md
  - iOS取证:
      - 彩信/短信取证: iOS/sms.md
   - 工具介绍:
      - 介绍: tools/index.md
      - 面板一把梭: tools/PanelForensics.md
      - Autopsy: tools/autopsy.md
      - DumpIt: tools/dumpit.md
      - Everything: tools/everything.md
      - FTK Imager: tools/ftkimager.md
      - R-Studio Network: tools/rstudio.md
      - Stellar Data Recovery: tools/stellar-data-recovery.md
  - 赛题Writeup:
      - 赛题Writeup: writeup/index.md
      - 2022长安杯Writeup: writeup/2022changancup.md
      - 2023盘古石杯Writeup: writeup/2023pgs.md
      - 2023龙信杯Writeup: writeup/2023lxb.md
      - 2024龙信杯Writeup: writeup/2024lxb.md
      - 2024第四届FIC Writeup: writeup/2024fic.md
      - 2024盘古石杯: writeup/2024pgs.md
      - 2024第一届獬豸杯Writeup: writeup/2024xzb.md
      - 2024美亚杯: writeup/2024myb.md
      - 2024数证杯: writeup/2024szb.md
  - 开源程序解析:
      - 野火IM: open/yhim.md
